---
# proxy server
- name: setup proxy server
  hosts: proxy_server
  become: yes

  tasks:
    - name: installation of  nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: remove default configuration
      ansible.builtin.file:
        path: /etc/nginx/conf.d/default.conf
        state: absent # remove default configuration file to avoid conflicts

    - name: configure reverse proxy
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/proxy.conf # create new config file for proxy-pass
        content: |
          server {
              listen 326;
              server_name _;

              location / {
                  proxy_pass http://172.31.32.73;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }

    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true
# app server
# this script to install and configure app server
- name: setup app server
  hosts: app_server
  become: yes

  tasks:
    - name: install nginx php php-fpm
      ansible.builtin.dnf:
        name:
          - nginx
          - php
          - php-fpm
        state: present

    - name: remove default config
      ansible.builtin.file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: configure nginx for php
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/app.conf
        content: |
          server {
              listen 80;
              server_name _;
              root /var/www/html;
              index index.php index.html;

              location / {
                  try_files $uri $uri/ =404;
              }

              location ~ \.php$ {
                  include fastcgi_params;
                  fastcgi_pass unix:/run/php-fpm/www.sock;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              }
          }

    - name: deploy php page
      ansible.builtin.copy:
        dest: /var/www/html/index.php
    - name: restart services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: true
      loop:
        - nginx
        - php-fpm
# db server
# this script to install 
- name: setup db server
  hosts: db_server
  become: yes

  tasks:
    - name: install mariadb
      ansible.builtin.dnf:
        name: mariadb105-server
        state: present

    - name: start mariadb
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: true

    - name: create database # create FCT database
      ansible.builtin.shell: |
        mysql -u root -e "CREATE DATABASE IF NOT EXISTS FCT;"
